{***************************************}
{Decompiled by IDR v.2.5.3 beta         }
{IDR home page: http://kpnc.org/idr32/en}
{***************************************}
program mERP;

uses
  Forms,
  groupaddun in 'groupaddun.pas' {groupaddfrm},
  grouplistun in 'grouplistun.pas' {groupfrm},
  RpFormSetup in 'RpFormSetup.pas' {RPSetupForm},
  RpFormPreview in 'RpFormPreview.pas' {RavePreviewForm},
  RpFormStatus in 'RpFormStatus.pas' {RPStatusForm},
  listrep in 'listrep.pas' {listrepfrm},
  rep_add_frm in 'rep_add_frm.pas' {add_rep_frm},
  supplieraddun in 'supplieraddun.pas' {supplieraddfrm},
  supp_pic_addun in 'supp_pic_addun.pas' {supp_pic_addfrm},
  supplierpicun in 'supplierpicun.pas' {supplierpicfrm},
  footnoteun in 'footnoteun.pas' {footnotefrm},
  supplierun in 'supplierun.pas' {supplierfrm},
  barangviewun in 'barangviewun.pas' {barangviewfrm},
  custandcpun in 'custandcpun.pas' {custncpfrm},
  calendarun in 'calendarun.pas' {calendarfrm},
  projectaddun in 'projectaddun.pas' {projectaddfrm},
  projectun in 'projectun.pas' {projectfrm},
  belisupun in 'belisupun.pas' {belisupfrm},
  progressun in 'progressun.pas' {progressfrm},
  dmun in 'dmun.pas' {dm},
  useraddun in 'useraddun.pas' {useraddfrm},
  userlistun in 'userlistun.pas' {userlistfrm},
  passchangeun in 'passchangeun.pas' {passchangefrm},
  kategoriaddun in 'kategoriaddun.pas' {kategoriaddfrm},
  categorilistun in 'categorilistun.pas' {kategorifrm},
  barangaddun in 'barangaddun.pas' {barangaddfrm},
  barangmstrun in 'barangmstrun.pas' {barangmstrfrm},
  customeraddun in 'customeraddun.pas' {customeraddfrm},
  custpicaddun in 'custpicaddun.pas' {custpicaddfrm},
  custpicun in 'custpicun.pas' {custpicfrm},
  customerun in 'customerun.pas' {customerfrm},
  gudangpickun in 'gudangpickun.pas' {gudangpickfrm},
  jatuhtempoun in 'jatuhtempoun.pas' {jatuhtempofrm},
  orderdetailun in 'orderdetailun.pas' {detailorderfrm},
  polistun in 'polistun.pas' {polistfrm},
  inventoryviewun in 'inventoryviewun.pas' {inventoryviewfrm},
  jualun in 'jualun.pas' {jualfrm},
  gudangaddun in 'gudangaddun.pas' {gudangaddfrm},
  gudangun in 'gudangun.pas' {gudangfrm},
  inventoryun in 'inventoryun.pas' {inventoryfrm},
  invoicelistun in 'invoicelistun.pas' {invoicelistfrm},
  deliveryun in 'deliveryun.pas' {deliveryfrm},
  akunun in 'akunun.pas' {akunfrm},
  neracaun in 'neracaun.pas' {neracafrm},
  penawaranun in 'penawaranun.pas' {penawaranfrm},
  foot_globalun in 'foot_globalun.pas' {footnote_globalfrm},
  labarugiun in 'labarugiun.pas' {labarugifrm},
  glun in 'glun.pas' {glfrm},
  jabatanaddun in 'jabatanaddun.pas' {jabatanaddfrm},
  jobdesun in 'jobdesun.pas' {jobdesfrm},
  salary_level_tambahaddun in 'salary_level_tambahaddun.pas' {salaryleveltambahaddfrm},
  salaryleveltambahun in 'salaryleveltambahun.pas' {salaryleveltambahfrm},
  penguranggajiaddun in 'penguranggajiaddun.pas' {penguranggajiaddfrm},
  penguranggajiun in 'penguranggajiun.pas' {penguranggajifrm},
  salaryleveladdun in 'salaryleveladdun.pas' {salaryleveladdfrm},
  salary_levelun in 'salary_levelun.pas' {salarylevelfrm},
  bankaddun in 'bankaddun.pas' {bankaddfrm},
  bankun in 'bankun.pas' {bankfrm},
  ptkpaddun in 'ptkpaddun.pas' {ptkpaddfrm},
  ptkpun in 'ptkpun.pas' {ptkpfrm},
  deptaddun in 'deptaddun.pas' {deptaddfrm},
  deptun in 'deptun.pas' {deptfrm},
  karyawanaddun in 'karyawanaddun.pas' {karyawanaddfrm},
  karyawanun in 'karyawanun.pas' {karyawanfrm},
  pphaddun in 'pphaddun.pas' {pphaddfrm},
  pphun in 'pphun.pas' {pphfrm},
  salary_prosesun in 'salary_prosesun.pas' {salaryprosesfrm},
  salaryinputun in 'salaryinputun.pas' {salaryinputfrm},
  salaryrptun in 'salaryrptun.pas' {salaryrptfrm},
  akunviewun in 'akunviewun.pas' {akunviewfrm},
  jurnalumumun in 'jurnalumumun.pas' {jurnalumumfrm},
  dolistun in 'dolistun.pas' {dolistfrm},
  utamaun in 'utamaun.pas' {utamafrm},
  dsun in 'dsun.pas' {ds};

{$R *.RES}

begin
  Application.Run;
end.
