{***************************************}
{Decompiled by IDR v.2.5.3 beta         }
{IDR home page: http://kpnc.org/idr32/en}
{***************************************}
unit ZPlainMySqlConstants;

interface

uses
  Classes, Windows, Graphics;

type
  TMYSQL_CLIENT_OPTIONS = (CLIENT_LONG_PASSWORD, CLIENT_FOUND_ROWS, CLIENT_LONG_FLAG, CLIENT_CONNECT_WITH_DB, CLIENT_NO_SCHEMA, CLIENT_COMPRESS, CLIENT_ODBC, CLIENT_LOCAL_FILES, CLIENT_IGNORE_SPACE, CLIENT_CHANGE_USER, CLIENT_INTERACTIVE, CLIENT_SSL, CLIENT_IGNORE_SIGPIPE, CLIENT_TRANSACTIONS, CLIENT_RESERVED, CLIENT_SECURE_CONNECTION, CLIENT_MULTI_STATEMENTS, CLIENT_MULTI_RESULTS, CLIENT_OPT_18, CLIENT_OPT_19, CLIENT_OPT_20, CLIENT_OPT_21, CLIENT_OPT_22, CLIENT_OPT_23, CLIENT_OPT_24, CLIENT_OPT_25, CLIENT_OPT_26, CLIENT_OPT_27, CLIENT_OPT_28, CLIENT_OPT_29, CLIENT_OPT_30, CLIENT_REMEMBER_OPTIONS);

implementation

end.