# MySQL-Front 5.0  (Build 1.0)

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


# Host: 192.168.1.71    Database: merp
# ------------------------------------------------------
# Server version 5.0.27-community-nt

USE `merp`;
REPLACE INTO `kategori` VALUES (1,'COLOR TV');
REPLACE INTO `kategori` VALUES (4,'LCD TV');
REPLACE INTO `kategori` VALUES (5,'LED TV');
REPLACE INTO `kategori` VALUES (6,'LED TV 3D');
REPLACE INTO `kategori` VALUES (7,'REFRIGERATOR');
REPLACE INTO `kategori` VALUES (8,'WATER DISPENSER');
REPLACE INTO `kategori` VALUES (9,'WASHING MACHINE');
REPLACE INTO `kategori` VALUES (10,'AUDIO');
REPLACE INTO `kategori` VALUES (11,'FAN / KIPAS ANGIN');
REPLACE INTO `kategori` VALUES (12,'VENT');
REPLACE INTO `kategori` VALUES (13,'WATER PUMP');
REPLACE INTO `kategori` VALUES (14,'MICROWAVE OVEN');
REPLACE INTO `kategori` VALUES (15,'MAGIC COM');
REPLACE INTO `kategori` VALUES (16,'BLENDER');
REPLACE INTO `kategori` VALUES (17,'JUICER');
REPLACE INTO `kategori` VALUES (18,'ELECTRIC IRON');
REPLACE INTO `kategori` VALUES (19,'STEAM IRON');
REPLACE INTO `kategori` VALUES (20,'SHAVER DRY');
REPLACE INTO `kategori` VALUES (21,'VACUUM CLEANER');
REPLACE INTO `kategori` VALUES (22,'AIR PURIFIER');
REPLACE INTO `kategori` VALUES (23,'ACTIVE SPEAKER');
REPLACE INTO `kategori` VALUES (24,'DVD');
REPLACE INTO `kategori` VALUES (25,'MESIN CUCI');
REPLACE INTO `kategori` VALUES (26,'SMALL HOME APPLIANCES');
REPLACE INTO `kategori` VALUES (27,'AIR CONDITIONER');

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
